### ISSUE TITLE
hm..

### ISSUE THREAD

**Issue by elzershark** [Causch/ioBroker.network#1]
`

network.0 | 2018-11-02 14:33:39.505 | error | See the arp-scan homepage at http://www.nta-monitor.com/tools/arp-scan/
-- | -- | -- | --
network.0 | 2018-11-02 14:33:39.505 | error | Report bugs or send suggestions to arp-scan@nta-monitor.com
network.0 | 2018-11-02 14:33:39.505 | error | use "arp-scan --help" for detailed information on the available options.
network.0 | 2018-11-02 14:33:39.505 | error | command line, and also in the file specified with the --file option.
network.0 | 2018-11-02 14:33:39.505 | error | These different options for specifying target hosts may be used both on the
network.0 | 2018-11-02 14:33:39.505 | error | specify all hosts in the given network and mask.
network.0 | 2018-11-02 14:33:39.505 | error | inclusive range, or IPnetwork:NetMask (e.g. 192.168.1.0:255.255.255.0) to
network.0 | 2018-11-02 14:33:39.505 | error | IPstart-IPend (e.g. 192.168.1.3-192.168.1.27) to specify all hosts in the
network.0 | 2018-11-02 14:33:39.505 | error | in the given network (network and broadcast addresses included), or
network.0 | 2018-11-02 14:33:39.505 | error | specify the target as IPnetwork/bits (e.g. 192.168.1.0/24) to specify all hosts
network.0 | 2018-11-02 14:33:39.505 | error | The target hosts can be specified as IP addresses or hostnames. You can also
network.0 | 2018-11-02 14:33:39.505 | error | require root privilege.
network.0 | 2018-11-02 14:33:39.505 | error | arp-scan, because the functions that it uses to read and write packets
network.0 | 2018-11-02 14:33:39.505 | error | You will need to be root, or arp-scan must be SUID root, in order to run
network.0 | 2018-11-02 14:33:39.505 | error | the network interface IP address and netmask.
network.0 | 2018-11-02 14:33:39.505 | error | the --localnet option is used, in which case the targets are generated from
network.0 | 2018-11-02 14:33:39.505 | error | given, in which case the targets are read from the specified file instead, or
network.0 | 2018-11-02 14:33:39.505 | error | Target hosts must be specified on the command line unless the --file option is
network.0 | 2018-11-02 14:33:39.505 | error | Usage: arp-scan [options] [hosts...]
network.0 | 2018-11-02 14:33:39.505 | error | Error running arp 1 arp-scan: unrecognized option '-x'
network.0 | 2018-11-02 14:33:39.469 | info | Starting full arp scan
network.0 | 2018-11-02 14:33:39.468 | info | full scan: 10 minutes, presence: 10 seconds

`

**Comment by elzershark** [comment]
vorher sudo apt-get install arp-scan arping gemacht. Raspy

**Comment by elzershark** [comment]
Beim Deinstallieren : 
`

host.Elzershark | 2018-11-02 14:38:45.214 | error | Cannot write files: /opt/iobroker/iobroker-data/files/network.admin/_data.json: ENOENT: no such file or directory, open '/opt/iobroker/iobroker-data/files/network.admin/_data.json'
-- | -- | -- | --
host.Elzershark | 2018-11-02 14:38:45.214 | error | Cannot write files: /opt/iobroker/iobroker-data/files/network/_data.json: ENOENT: no such file or directory, open '/opt/iobroker/iobroker-data/files/network/_data.json'

`

**Comment by Causch** [comment]
Habe -x aus dem scan rausgenommen

**Comment by elzershark** [comment]
sicher?
gleicher fehler mit -x

**Comment by elzershark** [comment]
Installation Steps
go to your admin panel
select "install from custom url" / "Installieren aus eigener URL"
select tab "CUSTOM"
enter https://github.com/Causch/ioBroker.network/archive/master.zip
click install


Das funktioniert gar nicht.
muss so heißen:
enter https://github.com/Causch/ioBroker.network

**Comment by elzershark** [comment]
Aber da werden bei mir zu viele Fehler angezeigt schon beim installieren des Adapters und einfügen des Adapters.

**Comment by elzershark** [comment]
das untere "found 83 vu..." hat nichts mit dem Adapter zu tun. Das ignorieren

**Comment by elzershark** [comment]
läuft fehlerfrei jetzt :
install github = ok
install Adapter = ok
deinstall Instance = ok
deinstall Adapter = ok

Raspy
npm 6.4.1
admin 3.5.10

thx :)

**Comment by elzershark** [comment]
Installation Steps
go to your admin panel
select "install from custom url" / "Installieren aus eigener URL"
select tab "CUSTOM"
enter https://github.com/Causch/ioBroker.network/archive/master.zip
click install

Das funktioniert gar nicht.
muss so heißen:
enter https://github.com/Causch/ioBroker.network

Wer Installation Steps
go to your admin panel
select "install from custom url" / "Installieren aus eigener URL"
select tab "CUSTOM"
enter https://github.com/Causch/ioBroker.network/archive/master.zip
click install

Das funktioniert gar nicht.
muss so heißen:
enter https://github.com/Causch/ioBroker.network

wer https://github.com/Causch/ioBroker.network/archive/master.zip eingibt kann das nicht installieren

Wer https://github.com/Causch/ioBroker.network/archive/master.zip

**Comment by Causch** [comment]
ja, ich kann es gar nicht mehr über master.zip installieren, gibt nur noch fehler. Mit der .git url läuft es prima
